name: trust_food
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.7.0

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  flutter_web_plugins:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  convenience_types: ^0.6.3
  dio: ^5.8.0+1
  hooks_riverpod: ^2.6.1
  freezed: ^2.5.8
  freezed_annotation: ^2.4.4
  build_runner: ^2.4.15
  flutter_secure_storage: ^8.1.0
  flutter_bloc: ^9.1.0
  go_router: ^14.8.1
  device_preview: ^1.2.0
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  firebase_storage: ^12.4.4

  flutter_map: ^8.1.1
  latlong2: ^0.9.1   
  geolocator: ^10.1.0
  qr_flutter: ^4.1.0
  mobile_scanner: ^6.0.7
  web: ^1.1.1
  collection: ^1.19.1
  universal_html: ^2.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logo.png
    - assets/ambulante.png
    - assets/circle.png
    - assets/green_check.png
    - assets/left_arrow.png
    - assets/ler_qr.png
    - assets/map_home_user.png
    - assets/qr_code_1.png
    - assets/qr_code_2.png
    - assets/green_check.png
    - assets/left_arrow.png
    - assets/trustfoodlogo.png
    - assets/map_home_user.png
    - assets/star.png
    - assets/qr_code_1.png
    - assets/ambulante.png
    - assets/caldinho.png
    - assets/QRcodebutton.png
    - assets/qr_code_2.png
    - assets/circle.png
    - assets/ler_qr.png
    - assets/voltar.png
    - assets/ler_QR_Code_Button.png
    - assets/retangulo.png
    - assets/seller_point_map.png
    - assets/profile_button.png
    - assets/milho_do_ze_home.png
    - assets/milho_do_ze_gallery_1.png
    - assets/milho_do_ze_gallery_2.png
    - assets/pastel_do_seu_gustavo_home.png
    - assets/pastel_do_seu_gustavo_gallery_1.png
    - assets/pastel_do_seu_gustavo_gallery_2.png
    - assets/churros_da_neide_home.png
    - assets/churros_da_neide_gallery_1.png
    - assets/churros_da_neide_gallery_2.png
    - assets/lari_do_acai_home.png
    - assets/lari_do_acai_gallery_1.png
    - assets/lari_do_acai_gallery_2.png
    - assets/gallery.png
    - assets/toggle_on.png
    - assets/log_out_button.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
